# Generated by Django 3.2.23 on 2024-01-08 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookList',
            fields=[
                ('book_id', models.[編集済](primary_key=True, serialize=False)),
                ('book_isbn', models.CharField(max_length=13)),
                ('book_title', models.CharField(max_length=255)),
                ('book_creator', models.CharField(max_length=255)),
                ('book_publisher', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='booklist',
            constraint=models.UniqueConstraint(fields=('book_isbn', 'user'), name='unique_book'),
        ),
    ]
